### ISSUE TITLE
Can't get auto populating working

### ISSUE THREAD

**Issue by pembeci** [edoburu/django-slug-preview#1]
Firstly, thanks for this plugin. Exactly what I needed for a project.

The issue is the input text is not updated from a related field in the same form as I expected.

Here is my relevant code: 
```python
class Company(models.Model):
    name = models.CharField(max_length=255)
    slug = SlugPreviewField("URL", populate_from="name", always_update=True)

class CompanyForm(SlugPreviewFormMixin, forms.ModelForm):
    class Meta:
        model = Company
        fields = ['name', 'slug', 'website', 'email', 'rating', 'files_path', 'created_by']
```
I can see that slug_preview.js is attached and slug input text is:
```html
<input data-populate-from="name" data-url-format="None" id="id_slug" maxlength="50" name="slug" data-always-update="" required="" type="text">
``` 
but populating from is not working.

**Comment by vdboor** [comment]
These data attributes require the use of JavaScript, which is typically available in the Django admin. Are you using the form outside of the Django admin?

**Comment by pembeci** [comment]
Oh gosh. It has been a while. I was using it in the admin pages but I don't remember other details about the problem. I think slug previews was not a requirement and I just stopped using this after trying some. May be problem was completely because of my setup. So I'll just close the issue for now but thanks anyway.
